// Maps tech names to simple-icons CDN slugs for colorful brand icons
const techSlugs: Record<string, string> = {
  javascript: "javascript",
  typescript: "typescript",
  react: "react",
  "react native": "react",
  nextjs: "nextdotjs",
  "next.js": "nextdotjs",
  node: "nodedotjs",
  "node.js": "nodedotjs",
  nodejs: "nodedotjs",
  python: "python",
  django: "django",
  flask: "flask",
  fastapi: "fastapi",
  go: "go",
  rust: "rust",
  java: "openjdk",
  kotlin: "kotlin",
  swift: "swift",
  php: "php",
  ruby: "ruby",
  rails: "rubyonrails",
  html: "html5",
  css: "css3",
  tailwind: "tailwindcss",
  tailwindcss: "tailwindcss",
  sass: "sass",
  vue: "vuedotjs",
  angular: "angular",
  svelte: "svelte",
  vite: "vite",
  webpack: "webpack",
  postgres: "postgresql",
  postgresql: "postgresql",
  mysql: "mysql",
  mongodb: "mongodb",
  redis: "redis",
  sqlite: "sqlite",
  supabase: "supabase",
  firebase: "firebase",
  prisma: "prisma",
  graphql: "graphql",
  docker: "docker",
  kubernetes: "kubernetes",
  aws: "amazonwebservices",
  gcp: "googlecloud",
  azure: "microsoftazure",
  vercel: "vercel",
  netlify: "netlify",
  cloudflare: "cloudflare",
  git: "git",
  github: "github",
  gitlab: "gitlab",
  linux: "linux",
  ubuntu: "ubuntu",
  bash: "gnubash",
  nginx: "nginx",
  whatsapp: "whatsapp",
  telegram: "telegram",
  twilio: "twilio",
  stripe: "stripe",
  openai: "openai",
  framer: "framer",
  figma: "figma",
  expo: "expo",
  flutter: "flutter",
  dart: "dart",
  redux: "redux",
  jest: "jest",
  vitest: "vitest",
  // Extended brand mappings
  "react / next.js": "react",
  "next.js / react": "nextdotjs",
  heroku: "heroku",
  render: "render",
  koyeb: "koyeb",
  railway: "railway",
  replit: "replit",
  "github pages": "github",
  "github actions": "github",
  "github packages": "github",
  "google cloud": "googlecloud",
  "cloudflare cdn": "cloudflare",
  "cloudflare r2": "cloudflare",
  "cloudflare pages": "cloudflare",
  "cloudflare workers": "cloudflare",
  "cloudflare workers ai": "cloudflare",
  "cloudflare ai": "cloudflare",
  "cloudflare dns": "cloudflare",
  "cloudflare ddos protection": "cloudflare",
  "cloudflare waf": "cloudflare",
  "cloudflare zero trust": "cloudflare",
  "cloudflare tunnel": "cloudflare",
  "cloudflare turnstile": "cloudflare",
  "cloudflare images": "cloudflare",
  "cloudflare stream": "cloudflare",
  "vercel blob": "vercel",
  "aws / r2": "amazonwebservices",
  "amazonwebservices": "amazonwebservices",
  vps: "linux",
  deepseek: "deepseek",
  anthropic: "anthropic",
  "claude ai": "anthropic",
  "openai / chatgpt api": "openai",
  "openai/chatgpt api": "openai",
  "gemini api": "google",
  "google ai studio": "google",
  google: "google",
  "grok ai": "x",
  x: "x",
  lovable: "react",
  bolt: "stackblitz",
  dazle: "react",
  "replit ai": "replit",
  nodedotjs: "nodedotjs",
  nextdotjs: "nextdotjs",
};

export const TechIcon = ({ name, className = "w-3.5 h-3.5" }: { name: string; className?: string }) => {
  const slug = techSlugs[name.toLowerCase().trim()];
  if (!slug) return null;
  return (
    <img
      src={`https://cdn.simpleicons.org/${slug}`}
      alt={name}
      className={className}
      loading="lazy"
      onError={(e) => { (e.currentTarget as HTMLImageElement).style.display = "none"; }}
    />
  );
};
