kind = "web"
previewPath = "/"
title = "Darrell Mucheri Portfolio"
version = "1.0.0"
id = "artifacts/darrellm"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 24839

[services.development]
run = "pnpm --filter @workspace/darrellm run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/darrellm", "run", "build" ]
publicDir = "artifacts/darrellm/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "24839"
BASE_PATH = "/"
